### ISSUE TITLE
Conjuntos vazios sendo criados

### ISSUE THREAD

**Issue by luansimoes** [Moutella/es2rmkb#28]

**Comment by Moutella** [comment]
Missing reference exception [nessa linha](https://github.com/Moutella/es2rmkb/blob/fb2e7d985b56ee9d847f9f35644bf197ec4dea11/Assets/Scripts/controladorPeca.cs#L76)

**Comment by Moutella** [comment]
A referencia acima se se refere a outro bug

**Comment by Moutella** [comment]
Investigando aqui, quando é criado um conjunto e a peça volta a mão, este conjunto não está sendo deletado do tabuleiro lógico, somente dos visuais

**Comment by luansimoes** [comment]
Esse bug me parece ter sido corrigido de fato em 2672e8b.
