### ISSUE TITLE
Clicar em uma peça no modo peça desativa os scripts dela

### ISSUE THREAD

**Issue by Moutella** [Moutella/es2rmkb#30]
Como recriar: 

1. crie um conjunto
2. selecione a peça
3. solte e aperte denovo na peça
3. verifique no inspector as classes desativadas

informações extras: só ocorre quando está no modo de clicar peça, quando é diretamente no conjunto não ocorre esse problema

**Comment by luansimoes** [comment]
closed by commit b68032e
