### ISSUE TITLE
Erro de coleção modificada durante a iteração

### ISSUE THREAD

**Issue by luansimoes** [Moutella/es2rmkb#32]
Em alguns momentos, é retornado um erro em funções que utilizam um "foreach" e alteram o array dentro do loop.

Uma forma de reproduzir é executando o código no método sorteiaPrimeiroJogador com a chamada ao método removeCoringas descomentada.

InvalidOperationException: Collection was modified; enumeration operation may not execute.

**Comment by Moutella** [comment]
Fixado no 80e1034
