### ISSUE TITLE
Mudança de cor do coringa no rollback em grupos

### ISSUE THREAD

**Issue by Moutella** [Moutella/es2rmkb#36]
Jogada na mesa já no backup: 
![image](https://user-images.githubusercontent.com/19677195/59162252-1ad68400-8ac4-11e9-840b-77c913976333.png)
Depois do rollback:
![image](https://user-images.githubusercontent.com/19677195/59162259-2c1f9080-8ac4-11e9-88a1-7b84af6d46fe.png)

Só ocorre em grupos, não em sequências

**Comment by Moutella** [comment]
Potencialmente fixada no 5e6be89c2e65ae49ffb2658f60a61effecbe5b8a

**Comment by Moutella** [comment]
Fechado errado

**Comment by luansimoes** [comment]
Não consegui reproduzir o bug, porque o rollback aqui está dando "object reference not set to an instance of object"
