### ISSUE TITLE
Integração da lógica com a Interface(0)

### ISSUE THREAD

**Issue by Moutella** [Moutella/es2rmkb#8]

**Comment by Moutella** [comment]
> Falta:
> 
> * Adicionar um conjunto em outro conjunto
> * Criar um conjuntoInterface para o conjunto criado pela funcao logicaConjunto.divide
> * Ajeitar posicionamento ao adicionar/remover peças
> * Remoção de conjuntos vazios [BUG]
> * Comprar peça
> * Sistema de limitar de quem é a vez

Após o commit ad6ab8d, temos:

- [ ] Adicionar um conjunto em outro conjunto
- [x] Criar um conjuntoInterface para o conjunto criado pela funcao logicaConjunto.divide
- [x] Ajeitar posicionamento ao adicionar/remover peças 
- [x] Remoção de conjuntos vazios [BUG]
- [ ] Comprar peça
- [ ] Sistema de limitar de quem é a vez

**Comment by luansimoes** [comment]
closed by commit ad6ab8d
